version: '3'

services:
  db:
    image: postgres
    hostname: db
    volumes:
      - ./database:/var/lib/postgresql/data
  web:
    build: .
    hostname: web
    command: ./start.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db