# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 11:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import portfolio_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=100)),
                ('full_description', models.TextField(blank=True, max_length=1000)),
                ('tech_stack', models.CharField(max_length=200)),
                ('role', models.TextField(max_length=300)),
                ('private', models.BooleanField(default=False)),
                ('live_url', models.URLField(blank=True)),
                ('repo_url', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=portfolio_api.models.file_upload_path)),
                ('caption', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_api.Project')),
            ],
        ),
    ]
